development:
  address: mailhog
  port: 8025
  user_name: "user"
  password: "password"
  authentication: "plain"
  domain: "example.com"
  outgoing_address: "canvas@example.com"
default_name: "Instructure Canvas"
