common: &common
  address: mail
  port: 1025
  user_name: "user"
  password: "password"
  authentication: "plain"
  domain: "example.com"
  outgoing_address: "canvas@example.com"

development:
  <<: *common

production:
  <<: *common

test:
  <<: *common

default_name: "Instructure Canvas"
