common: &default
  # This is a pre-generated random key required by canvas.
  encryption_key: <%= ENV["ENCRYPTION_KEY"] %>
  lti_iss: 'https://canvas.instructure.com'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default